name: DartCI when push tag

on:
  push:
    tags:
      - v*

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./
      - name: Format code
        run: flutter format --set-exit-if-changed .
        working-directory: ./
      - name: Static analysis
        run: flutter analyze
        working-directory: ./
      - name: Flutter tests
        run: flutter test
        working-directory: ./
      - name: Flutter build Android
        run: flutter build apk
        working-directory: ./
      # - name: Push APK to Releases
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/flutter-apk/*.apk"
      #     token: ${{ secrets.TOKEN }}
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Tag Release
        run: |
          version_name=${GITHUB_REF##*/}
          echo "Tagging release with tag $version_name"
          git tag $version_name release/$version_name
          git push origin --tags
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.jshvarts.flows
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: alpha
          whatsNewDirectory: distribution/
